### ISSUE TITLE
ESM

### ISSUE THREAD

**Issue by kkonsolakis** [denzilferreira/aware-micro#2]
Until now, the client can read scheduler items from the configuration file, but not yet ESMs. 
ESMs need to be included, too.

**Comment by denzilferreira** [comment]
A Scheduler can have ESM items inside, so you can schedule the ESM delivery. ESM on their own will be presented immediately so you need to use them in tandem, e.g.,:
https://github.com/PennLINC/mobilephenomics/blob/master/code/ESMsforAWARE/withoutfamilyfinalpilot.json
