### ISSUE TITLE
My ./gradlew run stuck at 80%

### ISSUE THREAD

**Issue by yanzhanglee** [denzilferreira/aware-micro#5]
![image](https://user-images.githubusercontent.com/35453739/155182854-538bbd55-0b37-4ee1-a5cd-006db7996b43.png)

**Comment by lrasmus** [comment]
I think the server is still responding, it may just not have refreshed the "executing" status when it reaches 100%.  I realize this is a few months old, but were you able to get it working?

**Comment by denzilferreira** [comment]
Closing this as this is just Gradle that stays at 80% sometimes, even though server is running.
