### ISSUE TITLE
How can I test a server without the mobile client?

### ISSUE THREAD

**Issue by reikoNeko** [denzilferreira/aware-micro#7]
I'm used to working with the previous server that had a web interface;  If I try to open a new installation (which has not yet created any tables in the database) and click the "join study " link in a web browser, it just shows a QR code leading to index.php/#/study_name.

Opening this in a browser produces a 405 error code.

Also, what recommendations do you have for using an Apache/NGINX proxy in front of the application?

**Comment by lrasmus** [comment]
Specifically for testing w/o a mobile client - do you mean not having to load this on a physical device?  If so, you could set up an emulator and run AWARE there.  Or do you mean looking at a way to test that bypasses any client, such as via Postman or curl?

**Comment by reikoNeko** [comment]
I'm a server monkey, so curl or python requests would be ideal.

**Comment by reikoNeko** [comment]
Btw, here's what I worked out for the Apache (2.4) proxy; I'm guessing putting a path on our server like ${hostname}/aware/ would cause problems with the mobile app? Or is that accounted for in the QR code scheme?

```
ProxyPreserveHost on
SSLProxyEngine    on

## Accept self-signed certificate
SSLVerifyClient none

## Fix hardcoded URLs returned by proxy
AddOutputFilterByType SUBSTITUTE text/html
Substitute s/localhost:8443/__hostname__/ni

ProxyPass         /server-status  !
ProxyPass         / https://localhost:8443/
ProxyPassReverse  / https://localhost:8443/
```

**Comment by denzilferreira** [comment]
This server relies on the client POST requests to automatically create the tables. Without a client, there are no tables. This allows us to create tables and not have to deal with migrations. All tables have the same schema now too for sensor data.
