### ISSUE TITLE
Does this project have a license declaration?

### ISSUE THREAD

**Issue by dmikurube** [denzilferreira/aware-micro#8]
Hi, thanks for the great work on the AWARE Framework!  I was interested in it, and looking into it.

One point that I wondered is: Does this `aware-micro` have a license declaration?

The older (archived) `aware-server` looks to be licensed under the Apache License 2.0 in its `README.md`, but I was not able to find any license declaration.  Is this `aware-micro` licensed under the same Apache License 2.0?

**Comment by denzilferreira** [comment]
Yes, it's Apache License 2.0
